# k8s/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base # Reference to the base manifests

patches:
  - target:
      kind: Deployment
      name: spring-app-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3 # More replicas for production for high availability
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: prod # Set Spring profile to 'prod'
      - op: add # Add an environment label
        path: /spec/template/metadata/labels/environment
        value: prod
      # You might want to adjust resource limits/requests for production
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"

# Add Ingress for production access (assuming you have an Ingress Controller like Nginx/Traefik)
# new (add new manifest files which are not in base)
# - prod-ingress.yaml # Create this file in k8s/overlays/prod/