# k8s/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    app: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 80 # Service port (frontend port for cluster)
      targetPort: 8080 # Container port (backend port of your app)
  type: ClusterIP # Default, only accessible within the cluster