name: Deploy Spring Boot to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g., ghcr.io/owner/repo/image:sha)'
        required: true
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  KUBE_CONFIG: /tmp/kubeconfig

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: chrislennon/setup-kubectl@v2
        with:
          version: '1.28.0'

      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.3.0'

      - name: Decode and setup kubeconfig
        run: echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $KUBE_CONFIG

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$KUBE_CONFIG" >> $GITHUB_ENV

      - name: Set image in kustomization
        run: |
          cd k8s/overlays/${{ github.event.inputs.environment }}
          kustomize edit set image springboot-app=${{ github.event.inputs.image_tag }}

      - name: Deploy to Kubernetes
        run: |
          cd k8s/overlays/${{ github.event.inputs.environment }}
          kubectl apply -k .
