# .github/workflows/deploy-k8s.yml (ใน my-cicd-configs repo)
name: Deploy Spring Boot to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g., ghcr.io/owner/repo/image:sha)'
        required: true
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment configs
        uses: actions/checkout@v4

      # *** เพิ่ม Step นี้เข้ามาตรงนี้ครับ ***
      - name: Debug - List files in workspace
        run: |
          echo "Current working directory:"
          pwd
          echo "Files and directories in workspace:"
          ls -R .
        # ***********************************

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Apply Kubernetes Manifests for ${{ github.event.inputs.environment }}
        run: |
          # ใช้ Environment Variable GITHUB_WORKSPACE ซึ่งเป็น Absolute Path ของ Root Repository ที่ Checkout มา
          # GITHUB_WORKSPACE จะมีค่าเป็น /home/runner/work/bittema-pipeline-config/bittema-pipeline-config
          OVERLAY_PATH="${{ github.workspace }}/k8s/overlays/${{ github.event.inputs.environment }}"
          echo "Attempting to build Kustomize from absolute path: $OVERLAY_PATH"

          # ตรวจสอบว่าไดเรกทอรีนี้มีอยู่จริงหรือไม่ ก่อนที่จะเรียก kustomize
          if [ ! -d "$OVERLAY_PATH" ]; then
            echo "ERROR: The directory '$OVERLAY_PATH' does not exist! Please check your repository structure or workflow path."
            exit 1
          fi

          # รัน kustomize build ด้วย Absolute Path
          kustomize build "$OVERLAY_PATH" \
            | sed "s|YOUR_DOCKER_IMAGE_PLACEHOLDER|${{ github.event.inputs.image_tag }}|g" \
            | kubectl apply -f -
        env:
          KUBECONFIG: ~/.kube/config

      - name: Verify Deployment (Optional)
        run: |
          echo "Verifying deployment for ${{ github.event.inputs.environment }} environment..."
          kubectl get deployments -n default
          kubectl get services -n default
          kubectl rollout status deployment/spring-app-deployment -n default
        env:
          KUBECONFIG: ~/.kube/config
