# .github/workflows/deploy-k8s.yml (ใน my-cicd-configs repo)
name: Deploy Spring Boot to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g., ghcr.io/owner/repo/image:sha)'
        required: true
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

# .github/workflows/deploy-k8s.yml (ใน my-cicd-configs repo)
name: Deploy Spring Boot to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g., ghcr.io/owner/repo/image:sha)'
        required: true
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo (my-cicd-configs)
        uses: actions/checkout@v4

      - name: Checkout manifests repo (bittema-pipeline-config)
        uses: actions/checkout@v4
        with:
          repository: irbbook/bittema-pipeline-config
          path: bpc  # 👈 path ที่ไม่ซ้ำชื่อ repo

      - name: Debug - List files in workspace
        run: |
          echo "PWD: $(pwd)"
          echo "List root:"
          ls -R .

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Apply Kubernetes Manifests
        run: |
          OVERLAY_PATH="${{ github.workspace }}/bpc/k8s/overlays/${{ github.event.inputs.environment }}"
          echo "Attempting to build Kustomize from: $OVERLAY_PATH"

          if [ ! -d "$OVERLAY_PATH" ]; then
            echo "❌ ERROR: Directory not found: $OVERLAY_PATH"
            exit 1
          fi

          kustomize build "$OVERLAY_PATH" \
            | sed "s|YOUR_DOCKER_IMAGE_PLACEHOLDER|${{ github.event.inputs.image_tag }}|g" \
            | kubectl apply -f -
        env:
          KUBECONFIG: ~/.kube/config
