name: Deploy Spring Boot to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g., ghcr.io/owner/repo/image:sha)'
        required: true
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.11' # Try a different stable version

      - name: Download Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}

      - name: Set image in kustomization
        run: |
          cd k8s/overlays/${{ github.event.inputs.environment }}
          kustomize edit set image springboot-app=${{ github.event.inputs.image_tag }}

      - name: Deploy to Kubernetes
        run: |
          cd k8s/overlays/${{ github.event.inputs.environment }}
          kubectl apply -k .
