# .github/workflows/deploy-k8s.yml (ใน my-cicd-configs repo)
name: Deploy Spring Boot to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g., ghcr.io/owner/repo/app:sha)'
        required: true
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment configs
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }} # Secret ที่เก็บ kubeconfig

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Apply Kubernetes Manifests for ${{ github.event.inputs.environment }}
        run: |
          ENV_PATH="k8s/overlays/${{ github.event.inputs.environment }}"
          echo "Applying manifests from: $ENV_PATH"

          # ใช้ kustomize build เพื่อสร้าง final manifest
          # และ sed เพื่อแทนที่ image placeholder ด้วย image tag จริง
          kustomize build $ENV_PATH \
            | sed "s|YOUR_DOCKER_IMAGE_PLACEHOLDER|${{ github.event.inputs.image_tag }}|g" \
            | kubectl apply -f -
        env:
          KUBECONFIG: ~/.kube/config # ensure kubectl uses the correct config

      - name: Verify Deployment (Optional)
        run: |
          echo "Verifying deployment for ${{ github.event.inputs.environment }} environment..."
          kubectl get deployments -n default
          kubectl get services -n default
          # Wait for deployment to be ready (replace spring-app-deployment with your deployment name)
          kubectl rollout status deployment/spring-app-deployment -n default
        env:
          KUBECONFIG: ~/.kube/config